[package]
name = "hashicorp-lru"
version = "0.1.5"
authors = ["Al Liu <scygliu1@gmail.com>"]
description = "This is a Rust implementation for HashiCorp's golang-lru. LRUCache, TwoQueueCache and AdaptiveReplacementCache"
homepage = "https://github.com/al8n/hashicorp-lru"
repository = "https://github.com/al8n/hashicorp-lru.git"
documentation = "https://docs.rs/hashicorp-lru/"
readme = "README.md"
license = "MIT or Apache-2.0"
keywords = ["lru", "cache", "2q", "arc-cache", "algorithms", "data-structures"]
categories = ["lru", "cache", "2q", "arc-cache", "algorithms", "data-structures"]
edition = "2018"


[[bench]]
name = "lru_cache"
harness = false

[[bench]]
name = "two_queue_cache"
harness = false

[[bench]]
name = "arc_cache"
harness = false

[[example]]
name = "lru_cache"
path = "examples/lru_cache.rs"

[[example]]
name = "hit_ratio"
path = "examples/hit_ratio.rs"

[features]
default = ["hashbrown"]
nightly = ["hashbrown", "hashbrown/nightly"]

[dependencies]
hashbrown = {version = "0.11.2", optional = true}

[dev-dependencies]
scoped_threadpool = "0.1.*"
stats_alloc = "0.1.*"
rand = "0.8.4"
criterion = "0.3.5"
fnv = "1.0.7"
rustc-hash = "1.0"