[package]
name = "hashicorp-lru"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["hashbrown"]
nightly = ["hashbrown", "hashbrown/nightly"]

[[example]]
name = "lru_cache"
path = "examples/lru_cache.rs"

[dependencies]
hashbrown = {version = "0.11.2", optional = true}

[[bench]]
name = "lru_cache"
harness = false

[[bench]]
name = "two_queue_cache"
harness = false

[[bench]]
name = "arc_cache"
harness = false

[dev-dependencies]
scoped_threadpool = "0.1.*"
stats_alloc = "0.1.*"
rand = "0.8.4"
criterion = "0.3.5"
fnv = "1.0.7"
rustc-hash = "1.0"